### ISSUE TITLE
associate datatype to the observation values

### ISSUE THREAD

**Issue by aftiqb** [LATC/EU-data-cloud#1]
Reported by [Soren Roug](https://github.com/sorenroug)
It would be nice if the sdmx-measure:obsValue properties had a relevant rdf:datatype. As you see I have to convert to xsd:decimal in the query.” It would indeed be good if we could create typed literals for the obsValues, but I'm not sure if we can find out the datatype of the observations from the SDMX metadata. The query is :

PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#
PREFIX qb: http://purl.org/linked-data/cube#
PREFIX e: http://ontologycentral.com/2009/01/eurostat/ns#
PREFIX sdmx-measure: http://purl.org/linked-data/sdmx/2009/measure#
PREFIX skos: http://www.w3.org/2004/02/skos/core#
PREFIX g: http://eurostat.linked-statistics.org/ontologies/geographic.rdf#
PREFIX dataset: http://eurostat.linked-statistics.org/data/
SELECT ?nuts2
       SUM(xsd:decimal(?pop)) AS ?population
       ?wateruse
       xsd:decimal(?wateruse)*1000000/SUM(xsd:decimal(?pop)) AS 
 ?percapita WHERE {  ?observation qb:dataset dataset:demo_r_pjanaggr3 ;
        e:time http://eurostat.linked-statistics.org/dic/time#2007;
        e:age http://eurostat.linked-statistics.org/dic/age#TOTAL; 
        e:sex http://eurostat.linked-statistics.org/dic/sex#F;
        e:geo ?ugeo;
        sdmx-measure:obsValue ?pop.
  ?ugeo g:hasParentRegion ?parent.
  ?parent rdfs:label ?nuts2.
  ?wuregion qb:dataset dataset:env_n2_wu ;
            e:geo ?parent;
            e:cons http://eurostat.linked-statistics.org/dic/cons#W18_2_7_2; 
            e:time http://eurostat.linked-statistics.org/dic/time#2007;
        sdmx-measure:obsValue ?wateruse.
 } GROUP BY ?nuts2 ?wateruse ORDER BY DESC(?percapita)

**Comment by sorenroug** [comment]
To further complicate the problem is that notes to observation values are added as datatypes. I.e. some values have the datatype: &lt;http://eurostat.linked-statistics.org/dic/note#s>.
Try:
PREFIX sdmx-measure: &lt;http://purl.org/linked-data/sdmx/2009/measure#>

SELECT ?obs ?value DATATYPE(?value) AS ?datatype
FROM &lt;http://eurostat.linked-statistics.org/data/med_en22.rdf>
WHERE {
  ?obs sdmx-measure:obsValue ?value
 FILTER(DATATYPE(?value) != &lt;http://www.w3.org/2001/XMLSchema#string>)
}

A note should be a property of the observation resource. I.e. a query could look like this:

SELECT ?obsUri ?value ?note
FROM &lt;http://eurostat.linked-statistics.org/data/med_en22.rdf>
WHERE {
  ?obsUri sdmx-measure:obsValue ?value
   OPTIONAL { ?obsUri    sdmx-measure:note ?note }
}

And notes probably shouldn't be in the http://eurostat.linked-statistics.org/dic/note namespace unless Eurostat has standardised their note codes.

**Comment by cygri** [comment]
Regarding the “note” thingy being used as a datatype, see #11. It should go into an `obsStatus` property.

**Comment by aftiqb** [comment]
fixed in the following [commit](https://github.com/LATC/EU-data-cloud/commit/7981d975c13f86c616c8bb1db90a25c64ef0eb47)
