### ISSUE TITLE
Non-observed values in Eurostat

### ISSUE THREAD

**Issue by csarven** [LATC/EU-data-cloud#28]
re Aftab's note: "Certain data sets contains ‘-’ as the observation value. We treated such values (i.e., ‘-’) as 0 while representing observation vlaues in RDF."

It is interesting to know why - is turned into 0. They have different meanings and will be treated differently. My intuition tells me that - means that there is no value, however a 0 would indicate that's the actual observed value.

If such observations don't have an observed value, why were they kept in the dataset?

**Comment by aftiqb** [comment]
We assumed `-` to be `0` although we could be wrong with our assumption. If an observation has no value then Eurostat represents it with `:`. We ignored those observations where we encounter `:` while doing RDF transformation

**Comment by aftiqb** [comment]
k, it turned out that we were wrong with our assumption regarding `-`. In Eurostat, `-` refers to `not applicable`. check out the [special character document](http://epp.eurostat.ec.europa.eu/portal/page/portal/codes_special_values_changes/documents/after_9_March_flags_special_values.pdf) published by Eurostat. The document states:

`The previously used special value '-' = not applicable (incl. real zero) is no longer used in the online 
database; it has been replaced by the flag 'z'.`
