### ISSUE TITLE
time dimension construction problem

### ISSUE THREAD

**Issue by aftiqb** [LATC/EU-data-cloud#4]
[Soren Roug](https://github.com/sorenroug)

I believe there is a problem in this construction:
time rdf:resource="/dic/time#2004"
The part after the '#' is an NCName and therefore can't start with a digit

**Comment by sorenroug** [comment]
The time property is an unfortunate example to use as it would be more useful to create it as a literal like:
&lt;time>2004&lt;/time>

The problem however, occurs in other places as well:
&lt;unit rdf:resource="/dic/unit#1000T" />

**Comment by cygri** [comment]
I don't think this is an issue. The `fragment` part of a URI is not restricted to NCNames. It can be just about any combination of characters allowed in URIs.

(URIs of _properties_ where the local part isn't an NCName can't be serialized in RDF/XML. But this is only a problem for _properties_ and only a problem for RDF/XML; otherwise it's fine)
